# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'KeychainSwift', '~> 20.0'

  # Pods for Movies_MVVM

end
